# Criptomonedas que vamos a comparar
criptos = {
    "bitcoin": "BTCUSDT",
    "ethereum": "ETHUSDT",
    "binance coin": "BNBUSDT",
    "cardano": "ADAUSDT",
    "solana": "SOLUSDT",
    "ripple": "XRPUSDT",
    "polkadot": "DOTUSDT",
    "dogecoin": "DOGEUSDT",
    "litecoin": "LTCUSDT",
    "chainlink": "LINKUSDT",
    "shiba inu": "SHIBUSDT",
    "uniswap": "UNIUSDT",
    "stellar": "XLMUSDT",
    "usd coin": "USDCUSDT",
    "tether": "USDTUSDT",
    "monero": "XMRUSDT",
    "tron": "TRXUSDT",
    "vechain": "VETUSDT",
    "ethereum classic": "ETCUSDT",
    "algorand": "ALGOUSDT",
    "cosmos": "ATOMUSDT",
    "elrond": "EGLDUSDT",
    "aave": "AAVEUSDT",
    "zcash": "ZECUSDT",
    "celo": "CELOUSDT",
    "iota": "MIOTAUSDT",
    "maker": "MKRUSDT",
    "sushi": "SUSHIUSDT",
    "fantom": "FTMUSDT",
    "kava": "KAVAUSDT",
    "basic attention token": "BATUSDT",
    "harmony": "ONEUSDT",
    "the graph": "GRTUSDT",
    "nexo": "NEXOUSDT",
    "hbar": "HBARUSDT",
    "pancake swap": "CAKEUSDT",
    "zilliqa": "ZILUSDT",
    "curve dao token": "CRVUSDT",
    "compound": "COMPUSDT",
    "helium": "HNTUSDT",
    "yearn finance": "YFIUSDT",
    "safemoon": "SAFEMOONUSDT",
    "quack": "QUACKUSDT",
    "troy": "TROYUSDT",
    "serum": "SRMUSDT",
    "sand": "SANDUSDT",
    "chiliz": "CHZUSDT",
    "decentraland": "MANAUSDT",
    "arweave": "ARUSDT",
    "audius": "AUDIOUSDT",
    "alpha finance lab": "ALPHAUSDT",
    "anchor protocol": "ANCUSDT",
    "ren": "RENUSDT",
    "rari governance token": "RGTUSDT",
    "ocean protocol": "OCEANUSDT",
    "balancer": "BALUSDT",
    "hive": "HIVEUSDT",
    "lisk": "LSKUSDT"
}